version: '3'
services:
  nginx:
      image: nginx:image
      build:
          context: ./requirements/nginx
      container_name: nginx
      networks:
          - inception_network
      volumes:
        - wordpress:/var/www/wordpress
      depends_on:
          - wordpress
      ports:
          - 443:443
      restart: always

  mariadb:
      image: mariadb:image
      build:
          context: ./requirements/mariadb
      container_name: mariadb
      networks:
          - inception_network
      volumes:
        - database:/var/lib/mysql
      env_file:
        - .env
      restart: always

  wordpress:
      image: wordpress:image
      build:
          context: ./requirements/wordpress
      container_name: wordpress
      networks:
        - inception_network
      volumes:
        - wordpress:/var/www/wordpress
      depends_on:
        - mariadb
      env_file:
        - .env 
      restart: always

volumes:
    database:
        name: database
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/database
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/wordpress

networks:
    inception_network:
        driver: bridge

# **************************************************************************** #
# about latest tag and image: <service>:<tag> necessity:                       #
# https://vsupalov.com/docker-latest-tag/                                      #
# https://stackoverflow.com/questions/33816456/how-to-tag-docker-image-with-doc#
# ker-compose                                                                  #
# **************************************************************************** #