-- CREATE DATABASE DB;
-- CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';
-- GRANT ALL PRIVILEGES ON DB.* TO '$DB_USER'@'%';
-- FLUSH PRIVILEGES;

-- ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PASSWORD';

CREATE DATABASE IF NOT EXISTS DB;
-- CREATE USER 'kmeeseek'@'%' IDENTIFIED BY '876543';
GRANT ALL PRIVILEGES ON DB.* TO 'kmeeseek'@'%' IDENTIFIED BY '876543' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- ALTER USER 'root'@'localhost' IDENTIFIED BY '123456';